### ISSUE TITLE
Move bn-db repo into bn-api

### ISSUE THREAD

**Issue by mikethetike** [big-neon/bn-api#100]
This is an issue to facilitate discussion about moving the `bn-db` repo into `bn-api` as a sub folder. 

Currently we have the following problems of mismatched PRs in `bn-db`. 
- PR's in `bn-api` currently have to point to a different branch or fork of `bn-db` in order to pass travis builds
- PR's that are merged in `bn-db` will break PR's in `bn-api`.

These two repo's are very tightly coupled. The original reasoning for splitting them was to keep a hard separation of logic.

**Comment by mikethetike** [comment]
When there are a lot of PR's in both repo's it is difficult to know what order to merge. Merging them would definitely make this simpler.

**Comment by SWvheerden** [comment]
Currently we are having issues maintaining these two in sync, so there is definitely reason for merging them.  But that being said, I am still in favor of splitting them. This will make it easier if you want to not use postgress. If we keep the models separate we can easily swop out repo's by not pointing it to the current postgres repo.

**Comment by philipr-za** [comment]
As an example a fairly simple issue ( `#75` ) required a small change in `bn-db` that breaks the tests in `bn-api` so you would need to merge the `bn-db` change followed by the `bn-api` update. Logistically this could become a real pickle as more contributors join?

**Comment by SWvheerden** [comment]
We have two problems on them have two separate repo's:

1. bn-api requires code from bn-db, that means that bn-api will not build until your bn-db code has been merged in. This is the easier one of the two to fix. As we only force them to get bn-db  in first.
2. bn-db has changes that break bn-api. I see no way in which we can enforce fixes this way. We can only fix these with communication.

**Comment by Timo614** [comment]
I agree with the view of combining them personally. We could always break them apart later once it's more mature if there's some value at that point. :+1:

It does become a pain to sync them and the whole having to point to the fork from bn-api so tests pass has been a troublesome and error prone.

re: postgres vs something else -- we probably just need to modify the logic to use the Connection trait in place of the PgConnection https://docs.diesel.rs/diesel/connection/trait.Connection.html#implementors -- not sure if there would be any other gotchas to such a move but then at least we could make it more general in the API via the connection string and select the appropriate adapter.

Not sure of what value there would be to keep it separate unless we plan on using the crate alone in the future. Can't think of a good reason for that though unless someone knows of a use case there.

**Comment by Timo614** [comment]
It's a bit error prone with our current approach to point to a given fork for revisions as well. 

The guidance has been to point to a given fork so tests pass but in practice we're moving so fast that we end up pointing to the forks a lot. https://github.com/big-neon/bn-api/blob/master/.travis.yml#L33

Just opens the door to us developing locally on some bad fork which isn't ideal.

**Comment by mikethetike** [comment]
100% agree with @Timo614
