### ISSUE TITLE
When a ticket_type has it's remaining available allocation in a hold it should only be shown to the client after adding an access code

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#1029]
If you create a ticket type called "Media Passes" with a quantity of 100 and a price of $0. 
Then create a hold with 100 quantity. They should only show up to people after they have entered a code to "unlock" them.

**Comment by Timo614** [comment]
Should we close this in favor of #1059 and using private for these ticket types? It's possible people will mistakenly set them to public still so there could be some value it's just more explicit with that approach. Wondering if I should close my PR for this (should be set just not sure if the other configuration options may accomplish the same thing).

**Comment by Krakaw** [comment]
Closed in #1059

**Comment by Krakaw** [comment]
Closed in #1059
