### ISSUE TITLE
Allow `/users` to search by multiple params, not just email.

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#107]
Currently `/users` allows searching by email address. Sometimes we also need to search by ID.

For example when retrieving org details from `/organizations/${id}` we get `owner_user_id` but we need to display to an admin who the owner is.

An alternative for this case would be a join to return org owner details as well when calling `/organizations/${id}`. But we'll probably need a lookup on user ID sometime in the future.

**Comment by philipr-za** [comment]
Added in RP https://github.com/big-neon/bn-api/pull/121 
Added /users/{id} GET endpoint
