### ISSUE TITLE
Add new fields to /artists

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#108]
We need some extra fields in the model when creating and updating artists.

Frontend layout: https://sketch.cloud/s/dwaP2/all/promoter_artists/artists_new-artist

Missing fields:
- Bio
- Website url
- Facebook username
- Instagram username
- Snapchat username
- Soundcloud username
- Bandcamp username
- Youtube video (We might need multiple video links. So lookup table?)

**Comment by Timo614** [comment]
I'll take care of this one.

**Comment by Jasonvdb** [comment]
The way I'm passing youtube videos through to the api is just an array of URLs. Not sure it needs a separate table, could just store the array?
