### ISSUE TITLE
Add new fields to /events

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#109]
We need some extra fields in the model when creating and updating events.

Frontend design: https://sketch.cloud/s/dwaP2/all/promoter_events/events_create-event_add-support-artist

Basing the missing fields off the layout design above:
- Artist array [Artist ID, Set time]
- Door time
- Age limit
- Additional info
- Event status
- Event promo image URL
- Ticketing array [Name, Capacity, On sale time, Off sale time, Price in advanced, Price at the door, maximum allowed]
- Publish date (Null for immediately?)

**Comment by philipr-za** [comment]
Ticketing details will be available via Ticket Allocation api calls.
