### ISSUE TITLE
[Discussion] Create Integration tests that call the HTTP endpoints with JSON

### ISSUE THREAD

**Issue by mikethetike** [big-neon/bn-api#110]
In order to get a better check that the API is still working, I suggest we create a set of tests that creates an HTTP client and calls the endpoints directly, mimicking the web client directly. 

I think using the `actix_web` standard provided testing framework will be sufficient. (As opposed to using `hyper`)

I think it may also be worth using `cucumber_rust` to orchestrate the steps. Something like 

```gerkhin
Scenario: Invite Organization user
  Given I have obtained an access token with `OrgOwner` role
  And I have created an organization
 When I call invite organization user with email `test@test.com`
 Then I receive HTTP 201 Created
```

Some things to consider:

* How do we clear out the database before each test?

**Comment by CjS77** [comment]
I propose creating a `seed-db` executable that doubles as the API test by adding assertions to every API call. In this case, the DB is not cleared in between tests

**Comment by mikethetike** [comment]
We've created the bn-api-node repo for this.
