### ISSUE TITLE
Create facebook events

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#1134]
connects to big-neon/bigneon#39

One-Click facebook event creation

**Comment by philipr-za** [comment]
Allow for an Org to link their Facebook account

**Comment by zmelamed** [comment]
Docs here (These are private docs I'll need facebook account info to share access, ping me privately with a link to your facebook account so I can add you): https://developers.facebook.com/docs/pages/official-events/getting-started

Initially we're just creating the event and linking to our page to purchase. We'll need to capture the facebook event ID of the event that was created as part of our event model so 1) we can link to it from the studio event dashboard 2) so we can reference it when tracking conversation analytics (coming soon).

**Comment by mikethetike** [comment]
Waiting on a permission change on Facebook
