### ISSUE TITLE
More flexible age restriction

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#1135]
connects to big-neon/bigneon#44
@zmelamed Should we change this to a TEXT field so they can choose "Other" and type in their entry requirements?

**Comment by Krakaw** [comment]
Cache what they use previously so that we can re-use it for future events.

**Comment by zmelamed** [comment]
> Should we change this to a TEXT field so they can choose "Other" and type in their entry requirements?
Yes that's exactly what we need, Will need to coordinate this with the mobile app though because I believe they're expecting the number only. Let move it forward though, low hanging win

**Comment by mikethetike** [comment]
"low hanging win" :D
