### ISSUE TITLE
Promo codes

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#1136]
connects to big-neon/bigneon#45
@zmelamed do we need to maintain the face value for the reports?

**Comment by zmelamed** [comment]
Yeah they would be presented the same way as the holds with discounts in the reports. As a separate line item under the ticket type named after the promo code name. 

Does that make sense?

**Comment by Timo614** [comment]
This may actually be a dupe although there may be aspects we need to iterate on:
https://github.com/big-neon/bn-api/issues/446

https://github.com/big-neon/bn-api/blob/master/db/src/models/codes.rs

**Comment by philipr-za** [comment]
Yes, what you had done previously was mostly there. I have just been bringing it inline with the current design thinking and the way holds ended up working.
