### ISSUE TITLE
Add more fields to `/events/{id}`

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#118]
Right now this just returns: 
`{"id":"713f28fa-20cb-4d02-adf4-5c82e0c5bc56","name":"Some festival thing","organization_id":"2843e9cb-a2c5-4f59-af28-97c13519ec07","venue_id":"28c4a786-04af-455d-af42-c9e8accaf016","created_at":"2018-08-14T06:24:51.726977","ticket_sell_date":"2018-08-14T06:24:51.726977","event_start":"2018-08-30T10:00:00"}`

For a use to view all the details on an events page (https://sketch.cloud/s/dwaP2/all/fan_event-detail-page-edp/edp_onsale).

We need:
Organization name
All public artist fields (relies on artists being stored in events https://github.com/big-neon/bn-api/issues/109)
All venue fields

**Comment by mikethetike** [comment]
Add number of likes to this as well
