### ISSUE TITLE
Change Event Builder to use more realistic dates

### ISSUE THREAD

**Issue by mikethetike** [big-neon/bn-api#1210]
Currently the event_builder creates an event with default date in 2016, but the ticket sales start and  end around Utc::now +/- 2 days.

**Comment by Timo614** [comment]
@mikethetike this was mostly handled via https://github.com/big-neon/bn-api/pull/1200 I think?

The only date which seems off to me here is the publish date which is hardcoded to a date in 2018:
https://github.com/big-neon/bn-api/blob/master/db/src/test/builders/event_builder.rs#L47

Wasn't sure about this comment as well: https://github.com/big-neon/bn-api/blame/master/db/src/test/builders/event_builder.rs#L195

>             // TODO: The times should actually be linked to the event start date,
>            // but there are many tests that need to be updated to allow this

From the looks of the logic above and below it and it looks like the ticket pricing logic does use the dates that are based off of the start date which seems reasonable in the current logic.

```
        let event_start = self
            .event_start
            .unwrap_or(dates::now().add_days(2).finish());
        let event_end = self
            .event_end
            .unwrap_or(event_start.into_builder().add_days(2).finish());
```

```
        let event_start = self
            .event_start
            .unwrap_or(dates::now().add_days(-2).finish());
        let event_end = self
            .event_end
            .unwrap_or(event_start.into_builder().add_days(4).finish());
```

```
            let early_bird_start = cmp::max(
                self.sales_start.unwrap_or(times::zero()),
                dates::now().add_days(-2).finish(),
            );
            let early_bird_end = cmp::min(
                self.sales_end.unwrap_or(times::infinity()),
                dates::now().add_days(-1).finish(),
            );
            let standard_start = cmp::max(
                self.sales_start.unwrap_or(times::zero()),
                dates::now().add_days(-1).finish(),
            );
            let standard_end = cmp::min(
                self.sales_end.unwrap_or(times::infinity()),
                dates::now().add_days(2).finish(),
            );
```

**Comment by mikethetike** [comment]
Yeah, I created this ticket before I finished #1200. Originally all of the events were created in the past with the ticket sales dates being in the future which made no sense. The current settings are a lot better. I think we can close this issue for now
