### ISSUE TITLE
Get Email from Facebook Login

### ISSUE THREAD

**Issue by mikethetike** [big-neon/bn-api#122]
Currently we accept the facebook login token via the web, but we do not receive the email or the name and last name. We should retrieve these values from Facebook by making a call on the `bn-api` server and then populating the fields in the database.

**Comment by Timo614** [comment]
I'll grab this one.

**Comment by mikethetike** [comment]
@Timo614 I have a branch `mikethetike-fb-refactor` that fixes some of the server calls to FB, and replaces the `hyper` low level http client with `reqwest`. Feel free to use it or not as you see fit. Hopefully it helps, but I'm not too fussed if it isn't used. 
I didn't continue it because of the fact that we are using the web login for facebook, so server code wouldn't be used. Let me know what you think though

**Comment by Timo614** [comment]
Sounds good, thanks!
