### ISSUE TITLE
[Needs Investigation] Updating user profile triggers unique key constraint

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#1222]
We just need to check that if a user is updating their user profile, and they are _not_ changing their email address but have posted it along with the rest of their profile data, we must not trigger the unique key constraint.

![image](https://user-images.githubusercontent.com/41575888/56706454-546e4e00-6715-11e9-90d7-5a452392c223.png)

**Comment by Timo614** [comment]
I tried to reproduce this but I can update my user keeping my email address the same. I did however notice that if I try to switch my user email to one in user it triggers the database error which in turn returns the `users_email_key` causing the "Duplicate record exists" error on the frontend.

We could handle this better by having the code do a validation check instead to see if the email already exists and in that case just return it on the email field like we do for other validations.

Will quickly patch a validation for that to make the experience nicer.

My guess is the user in question already has another user account and tried to update this other account to use the same email the other is using.
