### ISSUE TITLE
You cannot refund a ticket twice (after a resale)

### ISSUE THREAD

**Issue by philipr-za** [big-neon/bn-api#1236]
Step's to reproduce
1) Sell a ticket_instance
2) Refund that ticket_instance
3) Sell that same ticket_instance again 
4) try to refund the ticket_instance.

You will get the error that the ticket has already been refunded.

Tricky to reproduce because the frontend doesn't give you the ability to pick a specific instance. If you sell and refund all the instances the next sale > refund cycle will produce the error.

**Comment by Krakaw** [comment]
To replicate this you could create a ticket_type with a quantity of 1.
