### ISSUE TITLE
Fees not included in refund email

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#1246]
What I bought
![image](https://user-images.githubusercontent.com/41575888/57175901-b172ae00-6e51-11e9-98a2-824b5ed82753.png)

What was refunded (the cash values are correct just the display is wrong)
![image](https://user-images.githubusercontent.com/41575888/57175818-74f28280-6e50-11e9-8402-66624a6335ff.png)

**Comment by mikethetike** [comment]
Related to #1253

**Comment by Anziskavds** [comment]
Tested on Beta, the refund amount still shows $0. Test failed on Beta

https://cl.ly/5cc045985ecc


Tested successfully on Develop.

https://cl.ly/5673be440737 

Develop is on 1.0.178 and Beta is still on 1.0.170. This is why it tested successful on Develop and not on Beta yet.

**Comment by Krakaw** [comment]
@Anziskavds beta updated to latest

**Comment by Anziskavds** [comment]
Tested successfully on Develop and Beta

https://cl.ly/cc994c3c0492

**Comment by Anziskavds** [comment]
Tested on Prod and is working as expected 

https://cl.ly/bd1908b65e1a
