### ISSUE TITLE
Transfers: Improve data model

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-api#1252]
The transfers data model isn't ideal. I should have made a single transfers record with multiple ticket instances linked via a transfer_ticket_instances table instead of a single transfers record per ticket instance tied back to the transfers_key. At the time I was mimicking the old per ticket instance setup we had but it's not ideal as it is denormalized and makes it harder for us to enforce uniqueness for the transfer_key.

This is unlikely to run into any issues so it's lower priority it just makes things a bit more difficult and prevents us from enforcing uniqueness across the transfer key so in the far future there could be collisions in the transfer_key space.

We should:
1. Add a `transfer_ticket_instances` table that links the transfer_id back to the ticket_instances
2. Have the SQL migration group by transfer_key and add any individual records for the above using a temp table to keep track of the main id per transfer key
3. Delete any records outside of that main id for those transfer keys
4. Set a unique index on the transfers key record
5. Adjust any broken logic as a result of the data model change

Sorry about that I should have thought more about it at the time but since I was working from the existing implementation I dropped the ball a bit in this regards.

**Comment by Krakaw** [comment]
@Tas4tari could you please convert this into an Epic and create issues for the outstanding items.

**Comment by Krakaw** [comment]
@Anziskavds this has been completed, it is part of the transfers / cancellation PR's if those pass, this is good to go.

**Comment by Anziskavds** [comment]
Reviewed:

-Tickets transferred successfully from one user to another

**Comment by Anziskavds** [comment]
Tested ticket transfer on Prod and ticket transferred successfully.
