### ISSUE TITLE
Transfers - A user should be able to cancel a ticket transfer they created until the transfer is accepted

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-api#1260]
connected to big-neon/bigneon#145

Context: If a user creates a ticket transfer request and that ticket has not yet been accepted/added to another users wallet, the transferrer should be able to cancel the transfer request

- When a user has a ticket in a transfer state they should be presented with an action button to `Cancel Transfer`.
- When a the `Cancel Transfer` button is clicked, the user should see a confirmation dialog `Are you sure you want to cancel this ticket transfer?`
- If the user clicks `Yes, cancel transfer`:
  - The transfer should be expired
  - A record of the transfer cancellation should be stored as part of that orders history
  - The transferrer should receive an email receipt that their ticket transfer was successfully cancelled.
  - The original transferee should receive a message through the channel the transfer was sent notifying them that the transfer was cancelled by the originating transferrer

Todo:
- Message to be sent notifying about transfer cancelled
- Email receipt about transfer being cancelled
- Linking a transfer back to an order
- Mark as cancelled
- #1252 should be handled here to make this clearer / easier to work with

**Comment by nine-tari** [comment]
The API changes have already been merged here. They were backwards compatible so should be safe / not blocked by the web side. Confirming with the team what we want to do going forward with the API side in these situations though as perhaps it makes more sense for us to hold merging (although it may become a nightmare for rebasing).

**Comment by Krakaw** [comment]
We'll get this process ironed out over the next couple of days. The PR is merged and ready for QA, which we have to do against the issue (you can't move a PR out of closed) this is purely to track what has been QA'd

**Comment by Anziskavds** [comment]
Reviewed on Beta and is working as expected.

**Comment by Anziskavds** [comment]
Tested on Prod and is working as expected.
