### ISSUE TITLE
Ticket Transfers - A ticket transfer should not expire automatically

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-api#1272]
connected to big-neon/bigneon#154

Context: A ticket transfer link should not expire until the transferrer or an admin manually cancels the transaction. Many people wait until the last minute to accept there transfer, thus transfer links expire causing confusion. The expiry is unnecessary.

**Comment by Anziskavds** [comment]
Reviewed and tickets no longer expires automatically. I waited 40 min after transferring a ticket and I still received the transferred ticket.

**Comment by Anziskavds** [comment]
Tested on Prod. Transferred tickets and waited a while before logging in to see if the tickets was transferred successfully or if it automatically expired. Tickets transferred successfully and didn't expire.
