### ISSUE TITLE
Mobile Guest List - A door person should be able to search by First Name, Last Name, or Full name

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-api#1283]
connected to big-neon/bigneon#165

**Context:** Currently you can only search by first name, as soon as you enter a space to begin typing the last name the results disappear. Typing just the last name returns no results.

**Acceptance Criteria:**
A door person should be able to find tickets belonging to John Smith by typing "John", "john s", "john smith", or "Smith"

related to ticket revelrylabs/bn-mobile-react#786

**Comment by Anziskavds** [comment]
Reviewed:

- A door person can search by first name and last name or by only the first name or last name.

**Comment by Timo614** [comment]
@Anziskavds see: https://github.com/big-neon/bigneon/issues/165#issuecomment-498214503

**Comment by Anziskavds** [comment]
Related to #165

Steps to reproduce:

- Door person can search for a guest in the guest list by first name and last name, last name and first name, last name and initials, initial and surname or by just the first name or last name on Develop environment.
- Door person can search for a guest in the guest list by only first name and last name, initial and last name, last name and initial or by just the first name or last name, it doesn't give any results if you search by the last name and then first name. This is both on Prod and Beta.

**Comment by Timo614** [comment]
I'm a bit confused with why this issue is failing.

I don't handle the releases so not sure if there's anything I can do here.

**Comment by Krakaw** [comment]
@Timo614 @Anziskavds I'll deploy the latest on beta if it works on develop I'm 99% sure it's because beta hasn't gotten the latest fixes.

**Comment by Anziskavds** [comment]
Reviewed and found that is working on the latest API 1.0.134

**Comment by Tas4tari** [comment]
This has been released 07 June 2019
