### ISSUE TITLE
Reporting - Audit Reports - Ticket counts section showing multiple rows for the same ticket type

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-api#1285]
connected to big-neon/bigneon#167

The report logic is grouping by ticket_pricing_id, name, and price but it should only be doing the latter two as we destroy and recreate the default pricing with each ticket type save to persist the old pricing data for already purchased order items to reference.

**Comment by Anziskavds** [comment]
Reviewed and pass

**Comment by Anziskavds** [comment]
Tested on Prod and it is no longer showing multiple rows of the same ticket type on the Event Audit Report.
