### ISSUE TITLE
Order Management - Order Management Redesign: Add Note

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-api#1302]
A user should be able to add a text note on an order which will show up on the timeline "Note added by [Org Member Name]

**Comment by Krakaw** [comment]
We should definitely keep track of
`order_id`
`user_id`
`created_by`
`created_at`
I would make the notes immutable so updates are in the form of another note attached to the user / order

**Comment by Timo614** [comment]
Either the PR I'll be pushing up today or https://github.com/big-neon/bn-api/pull/1321 will need to be modified whenever one of them gets merged as the notes fetching needs to be modified from the domain events to this separate table of notes I'll be adding here.

**Comment by Timo614** [comment]
@Krakaw We only want the ability to list and create these right? No soft deletes etc?

Or should org admins, org owners, and admins have that ability but normal org members can only list and create?

For the list of fields you mentioned both a `user_id` and a `created_by` did you mean for both or are they the same in this case?

**Comment by Timo614** [comment]
@Tas4tari 

FYI going to remove the existing order update endpoint that is only used for setting a note on the order. Confirmed via the logs that "PATCH orders -refund" is not currently being hit by any consumer. 

The old endpoint only allowed the note to be edited by an existing user. Or do we want to keep the old note and have that one be a customer set note versus these admin ones? Wondering if this functionality is a replacement of the old order note or entirely separate.

**Comment by Krakaw** [comment]
@Timo614 the `user_id` would be the user that created the order and `created_by` would be the studio user that created the note. I guess we could join the orders table to get the user_id but I was thinking for when we pull these notes for the fans it would be nice to denormalize this data.

**Comment by nine-tari** [comment]
This was merged but we're pending review until the frontend is set for it right? So will keep in progress for now.
