### ISSUE TITLE
New Orders/Fans Endpoint

### ISSUE THREAD

**Issue by shanimal08** [big-neon/bn-api#1307]
New endpoint for the relevant data needed for Fans and Orders.

**Activity types:** 

* Purchases: 
  - Order Number
  - Quantity
  - Event Information for the purchase
    - Name
    - Code
    - Quantity
    - Total (Price)

      
* Transfers:
  - Status - Pending, Successful, Cancelled.
  - Tickets
  - Initiated by
  - Transfer address
  - Accepted by/Cancelled by

            
* Check-ins
  - Checked in tickets

          
* Refunds:
  - Refund amount
  - Items refunded
  - Reason
  - Who refunded who

          
* Notes: 
  - Note 
  - Who added note
  - Which order

Grouped by Events for Fans.

Can look at [this](https://app.goabstract.com/projects/20f4bd60-ab00-11e8-b694-6fcb86ba37e4/branches/e2490f36-5e43-46c4-a62d-eebce3acd948/commits/88c91cd06bd9f8d7b0181cf5dfdaffd6c4307322/files/544D16EE-9C75-4DA0-83BA-D2C1A532A823/layers/A2746D74-8FBD-44EF-8ECE-D9AFE183C2D1?mode=design) for Activity types design and [this](https://sketch.cloud/s/ebkxW/a/4GMaQD/play) to see them grouped under events

**Comment by Jasonvdb** [comment]
Using the scope `order:read` for allowing access to the new order list. But that seems to be the one for viewing a specific order so If there's going to be a new scope for this endpoint let me know

**Comment by Jasonvdb** [comment]
API call for querying user and order details will always need to include `organization_id` I'm guessing.

So if a fan is attending an event for 2 different orgs, each org should only ever be able to view the activity for events belonging to their org.

@Tas4tari sounds right hey?

**Comment by Tas4tari** [comment]
@Jasonvdb  I believe so yes.

**Comment by Timo614** [comment]
@Jasonvdb What permissions should this endpoint have? Anyone with `OrderRead` should be able to access it? I think `OrgFans` permission may make more sense but it's a bit more restricted as Promoters can't access them then.

Is this something someone would access via the fans listing? That fans#index endpoint currently uses `OrgFans` so if that's the case probably safe for us to use that.

**Comment by Timo614** [comment]
We don't currently record Reason with the refunds. I'll add it as part of this branch as an optional String that can be provided to the refund endpoint.

**Comment by Jasonvdb** [comment]
@Tas4tari @zmelamed do you know which org roles is the order viewing/management for?

**Comment by Tas4tari** [comment]
@zmelamed would be able to provide us with context with regards to the org roles.

**Comment by zmelamed** [comment]
Org member and above

**Comment by nine-tari** [comment]
This may be safe to move into the review pile or completed. The changes were merged in but it's slowly being augmented as we change the needs there for frontend design. Probably easiest to just review via the frontend cards associated with the activity showing.
