### ISSUE TITLE
SMS for transfer cancel should use sender user not auth user

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-api#1308]
The logic associated with sending a transfer cancelled SMS currently uses the auth user to generate the full name of the user who has cancelled the tickets. Both admins and users can trigger a cancel on the API so this should be using the sending user not the auth user as it otherwise will use the admin's name not the sending user's name for the SMS.

Best way to test is just to cancel a different user's transfer as an admin (not your own or it would be the same).

**Comment by Tas4tari** [comment]
Closing as this has been completed and merged
