### ISSUE TITLE
Event Audit Report: Face value calculation incorrect

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-api#1310]
See: https://github.com/big-neon/bn-web/issues/1417

It should be ticket fee inclusive it also currently is showing a price for comps etc which it shouldn't as it's the price the user paid for the tickets including their fees.

**Comment by nine-tari** [comment]
Was merged a bit back fixes the issue which was causing bn-web to show an incorrect face and totals columns.

**Comment by Anziskavds** [comment]
Tested on Beta and the calculations is correct

**Comment by Anziskavds** [comment]
Tested on Prod and looks like the calculations are correct
