### ISSUE TITLE
`/admin/orders` endpoint for order list for an event.

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#1312]
Can pretty much work the same as current `/orders` endpoint but needs to accept `event_id` instead of just returning the current user's orders.

Required for big-neon/bn-web#1523
Design: https://share.goabstract.com/eb756c85-a087-4208-b3d3-ac4d5ca002a9?collectionLayerId=e6f5fc83-c651-48b7-be93-3db8123c34b3&mode=design

**Comment by Jasonvdb** [comment]
Sorry some more requests:
- [ ] Needs to also support a search query (Order #, Name,Email, Ticket #)
- [ ] Filter by ticket type
- [ ] Filter by promo code

**Comment by Jasonvdb** [comment]
Also need the user names (first+last) and the user email address.

**Comment by Jasonvdb** [comment]
And the point of sale. I think that's just `Online | App | BoxOffice`.

**Comment by Jasonvdb** [comment]
@mikethetike need the first name, last name, email, POS to each order

**Comment by Anziskavds** [comment]
To be tested with order management
