### ISSUE TITLE
Allow start_date to be null for ticket_types.

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#1324]
If we using the dropdown option of immediately it's currently causing date overlap issues if bn-web just sets start_date to the current time. A null value would work better/safer.

Related to: https://github.com/big-neon/bigneon/issues/183 and https://github.com/big-neon/bn-web/issues/1524#event-2400126180

**Comment by Anziskavds** [comment]
Tested on Prod and works as expected.
