### ISSUE TITLE
Event Dashboard - When a event ended information on graph should only show up to the last sale date

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#1325]
@Anziskavds commented on [Fri May 24 2019](https://github.com/big-neon/bn-web/issues/1482)

Steps to reproduce:

-When a event has ended the graph must only show up to the last sales date and no further

![Image Pasted at 2019-5-24 13-37.png](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/358dff8c-6b30-4f03-843f-bfd59ecd4e25)

**Comment by Anziskavds** [comment]
Tested on Beta and is working as expected on Beta but I didn't have enough data to test this on Prod and because of this I'm not comfortable with closing this issue.

**Comment by Tas4tari** [comment]
@harrisonlemon Could you please verify this in Production as we do not have the sufficient data in order to do so.

**Comment by harrisonlemon** [comment]
@Tas4tari Confirmed on production - working as expected. Thanks!

**Comment by Tas4tari** [comment]
@harrisonlemon Thank you
