### ISSUE TITLE
DRY up ticket receive link, adjust drip link

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-api#1332]
Related to #1329 

We updated the links for the receive URL at the same the drip functionality merged in so the new drip links are pointing to the incorrect old address. Used this as an opportunity to refactor the logic to make things a bit more straightforward for this / DRY it up.

Also noticed in the process that the mailer functionality for the drip was missing the accept link so added that in the associated branch.

**Comment by nine-tari** [comment]
Was merged last week -- it added the accept link to the transfer drips. Best way to test is to have someone with db access trigger the transfer drip early. A bit hard otherwise as it uses the distance from the start of the event to trigger.

**Comment by Anziskavds** [comment]
Tested on Beta and is working as expected.

**Comment by Anziskavds** [comment]
Tested on Prod and is working as expected.
