### ISSUE TITLE
Analytics/Sharing - Custom link generator for campaign tracking

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-api#1336]
Context: A promoter should be able to generate a custom trackable shortened URL through a link builder. The builder would have presets for tracking common channels like Facebook, Email, Twitter, Instagram, etc. and would applicable to shared promo/hold codes. This link would deeplink into the mobile app or web app and track the data up to the transaction.

**Comment by Anziskavds** [comment]
Tested Beta on Mobile web and Web. Tested successful on Beta.

**Comment by Anziskavds** [comment]
Tested on Prod and is working as expected
