### ISSUE TITLE
Fees - Event Level Fees

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-api#1338]
Context: More robust fee capabilities are now a need with All Aboard / Espee and Midway. Minimum org & event-level fee requirements:

1. We require the ability to add an additional fee per ticket type.
2. The amount allowed within the additional fee should be capped at $2.

**Comment by Anziskavds** [comment]
Tested Develop and Beta on both Web and Mobile web and is working as expected.

**Comment by Anziskavds** [comment]
Tested on Prod and is working as expected
