### ISSUE TITLE
API and DB functions need transactions

### ISSUE THREAD

**Issue by mikethetike** [big-neon/bn-api#134]
If an API call or DB method calls multiple methods to the database where data is changed, then they should all fail or succeed. This should be done using a transaction.

For example:
```rust
  pub fn create_from_external_login(
        external_user_id: String,
        site: String,
        access_token: String,
        conn: &Connectable,
    ) -> Result<User, DatabaseError> {
        let hash = PasswordHash::generate("random", None);
        let new_user = NewUser {
            first_name: String::from("Unknown"),
            last_name: String::from("Unknown"),
            email: NTone,
            phone: None,
            hashed_pw: hash.to_string(),
            role: vec![Roles::Guest.to_string()],
        };
        new_user.commit(&*conn).and_then(|user| {
            user.add_external_login(external_user_id, site, access_token, conn)?;
            Ok(user)
        })
    }
```
If the new user is created, then the `add_external_login call` fails, then the database is in an inconsistent state. 

This should be wrapped in a transaction.

**Comment by mikethetike** [comment]
Is it worth adding an actix middleware that begins and ends the transaction?

**Comment by mikethetike** [comment]
It might be worth checking out how this is done in crates.io https://github.com/rust-lang/crates.io/blob/master/src/models/krate.rs

**Comment by Timo614** [comment]
Grabbing -- will take a look at crates.io as a reference.

**Comment by mikethetike** [comment]
I also wasn't sure whether the closure would be possible in the API. I agree with your approach. I assume that the `response` logic in point 2 is the actix middleware response logic? You might be able to check for an error response at that point and then commit or rollback then, but see whatever is easiest to implement.

**Comment by Timo614** [comment]
Not sure if the Connection trait is going to work out it has two associated types with it so they would need to be specified whenever you use the trait object. But we can't even make a trait object with it anyhow as it requires Sized https://github.com/diesel-rs/diesel/blob/765b782f7f94932cf129bc603dc5909d7155e9fe/diesel/src/connection/mod.rs#L30

We could hardcode PgConnection in place of that abstraction if we'd like to go that route. Will just hold off on changing anything for it in this branch though I think for now and just get the transaction in place for the API per above.

**Comment by Timo614** [comment]
Yeah I'll have to use the middleware for the rollback as well as we have no access to the HttpRequest in the logic that converts the Db Error over to a BigNeonError for the http response. 

https://github.com/actix/actix-web/search?q=from_error&unscoped_q=from_error

We do use the trait which sets the error field for the response though so can use that to do the rollback so will go with that approach.

**Comment by mikethetike** [comment]
> Yeah I'll have to use the middleware for the rollback 
Happy.

> We could hardcode PgConnection in place of that abstraction if we'd like to go that route.
We are already heavily entrenched in postrgres anyway, so I don't think it'll be a massive problem to use it. If someone wanted to swap out for a different DB, they'd have to change most of the SQL migrations as well.
