### ISSUE TITLE
Event drip events, use separate templates for source and destination drips

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-api#1340]
Related to #1300 

We should be using separate templates for source and destination drips. I mistakenly thought we wanted to use the same across all drip ones with different headers but the templates have different layouts so we need them split.

In addition we'd like to break apart the sender_name into its own variable and receiver_address.

**Comment by Anziskavds** [comment]
Tested on Beta and is working as expected. Both the parties received notification emails that the transferred tickets haven't been claimed yet. The sender and receiver receive different  notification emails. Sender can cancel the transfer from the notification email and the receiver can claim their ticket/s from the notification email.

**Comment by Anziskavds** [comment]
Tested on Prod and is working as expected.
