### ISSUE TITLE
Transaction Detail Report does not include Credit Card fees

### ISSUE THREAD

**Issue by mikethetike** [big-neon/bn-api#1363]

**Comment by Krakaw** [comment]
We need to add another join after https://github.com/big-neon/bn-api/blob/97dc7f5dbb582012688736aedcb13956d2e35577/db/src/queries/reports/reports_transaction_details.sql#L60
```
LEFT JOIN order_items oi_cc_fees
                   ON (oi_event_fees.item_type = 'CreditCardFees' AND o.id = oi_event_fees.order_id)
```

**Comment by harrisonlemon** [comment]
@zmelamed The TDR should not expose cc processing fees. The fee breakouts should live in another fee-specific report

**Comment by zmelamed** [comment]
@harrisonlemon the TDR should include the credit card fee amount in the gross and total service fees though you're just saying it shouldn't break out the credit card fee into it's own column, correct?

**Comment by harrisonlemon** [comment]
@zmelamed The TDR is not the report to breakout fees in general. Right now, it is serving as a workaround fee breakout + transaction detail report. As we start to build out fee functionality, including fee breakouts in the TDR is going to become unwieldy. The TDR is also traditionally shared/exposed with outside promoters - we don't want to expose fee data of any kind. Fee reporting should exist in its own report

**Comment by Anziskavds** [comment]
Please advise if the credit card fees should or shouldn't show on the Transaction Detail Report
@Tas4tari @harrisonlemon @zmelamed

**Comment by Anziskavds** [comment]
Tested on develop and beta. Credit card fees is added to the service fees and appear under the service fee column on the Transaction Detail report. The correct amount appears in the gross(Ticket price + Service fee=Gross) column.

**Comment by Tas4tari** [comment]
@Anziskavds Can you please confirm this in Prod

**Comment by Anziskavds** [comment]
Tested on Prod and the calculations is correct on the Transaction Detail report. Credit card fees is added to the service fee. Tested successful on Prod.

**Comment by harrisonlemon** [comment]
The Transaction Detail Report historically will not contain credit card fee information or company service charge details. 

The TDR should only surface base ticket price + client rev share. 

Detailed fee reporting should live in another report: the Fee Breakout Report, not yet in existence in Big Neon.

**Comment by Anziskavds** [comment]
@harrisonlemon Just to make sure that I understand you correctly. What fees should reflect in the "service fee" column on the TDR report?

**Comment by harrisonlemon** [comment]
@Anziskavds The TDR traditionally includes client rev shares only. Will take discuss fee inclusion this week with the business team, and confirm which fees to include on the TDR. Thanks!

**Comment by harrisonlemon** [comment]
Hi @Anziskavds Confirmed with Dan: the TDR should only include client-facing revenue values (base ticket price + client rev share). The TDR should not include Big Neon service fees or credit card processing fees in the 'service fee' column. Thanks!

**Comment by Anziskavds** [comment]
@harrisonlemon Thank you for the feedback. I'll reopen and retest this issue.

**Comment by Anziskavds** [comment]
The TDR doesn't have the correct calculations as expected.

**Comment by Tas4tari** [comment]
This has been moved to Bug Backlog on Asana for prioritization
