### ISSUE TITLE
Add a slug to the event table to be used in URLs

### ISSUE THREAD

**Issue by mikethetike** [big-neon/bn-api#138]
Each event should have a unique URL (on the web, not the API) that helps with SEO rankings. 

@Jasonvdb suggested that we something like this:
```
http://site-domain/events/<description>_<event_id>
```
e.g.
```
http://site-domain/events/big-neon-launch-thrice_384ddaee0ee9eeeu33
```

It may or may not be necessary to store this description as a slug in the `events` table, since it can be generated on the fly.

**Comment by Jasonvdb** [comment]
I think store the slug rather? Then it's assured the same one is being used when retrieving event in the web, app and whatever else consumes the api. I think we'll need to optimise many other things before this becomes a problem one day

**Comment by philipr-za** [comment]
After discussion it was decided that this will be handled on the front-end.
