### ISSUE TITLE
Add 'Category' to events for website listings

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-api#1380]
Categories include:

Music
Art
Culinary
Comedy
Conference
Sports

Additional categories to be added at a later date as we grow.

**Comment by Tas4tari** [comment]
Tested on Develop, working as expected

**Comment by Anziskavds** [comment]
Tested successful on Beta on web and mobile web.

**Comment by Anziskavds** [comment]
Tested successful on Prod on web and mobile web
