### ISSUE TITLE
Ticket transfer receiver cancelled email template invalid vars

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#1383]
In the transfer cancelled template there is a missing variable for a name field it looks like. Not sure if this is from the API or in the template itself @zmelamed.

![image](https://user-images.githubusercontent.com/41575888/60752299-005cd100-9fc4-11e9-97c1-2d53e4faca89.png)

**Comment by Timo614** [comment]
Relates to:
https://github.com/big-neon/bigneon/issues/205
https://github.com/big-neon/bn-api/issues/1265

The latter has been blocked but not sure why. The code and some vars were added prior to the template being ready so it's not synced on its needs. Not sure why the issue ended up in a blocked state but should be a simple change. I can probably push something up if I can get sendgrid access to confirm the vars, will ask in the chatroom about that.

**Comment by Timo614** [comment]
`{{sender_name}}` is the only missing variable here from looking over the template. I'll have the logic populate all the other now default transfer fields in case we want to expand it later.

**Comment by Timo614** [comment]
It looks like this one was related to the template having "sendar_name" instead of "sender_name". I updated it to the correct spelling.

**Comment by nine-tari** [comment]
This was just merged so moving to QA pile.

**Comment by Anziskavds** [comment]
Tested Develop and Beta and the correct information appears on the transfer cancelation email.

https://cl.ly/b04b2be2971e

**Comment by Anziskavds** [comment]
Tested successful on Prod
