### ISSUE TITLE
Ticket transfer sender cancellation template issues

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#1384]
Missing a name (Because one was never entered)
![image](https://user-images.githubusercontent.com/41575888/60752317-24b8ad80-9fc4-11e9-86e3-098a3daea3cb.png)

**Comment by Timo614** [comment]
Relates to:
big-neon/bigneon#205
#1265

The latter has been blocked but not sure why. The code and some vars were added prior to the template being ready so it's not synced on its needs. I'll push something up to get this set since it should be a simple fix with the API vars.

**Comment by Timo614** [comment]
`{{receiver_address}}` is the only missing variable here from looking over the template. I'll have the logic populate all the other now default transfer fields in case we want to expand it later.

**Comment by nine-tari** [comment]
This was just merged so moving to QA pile.

**Comment by Anziskavds** [comment]
Tested Develop and Beta and both the transfer cancellation emails had the email address of the receiver(Person the transfer was sent to and cancelled).

https://cl.ly/826c4bd36b12

https://cl.ly/282187f04c71

**Comment by Anziskavds** [comment]
Tested on Prod and it tested successful
