### ISSUE TITLE
Prevent an event END TIMEs for events from being set before SHOWTIME during Event Build

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-api#1385]
Client was able to build an event with the End TIME set before SHOW TIME.

This only occurs during the initial Event Build and is reproducible
https://cl.ly/718ec25e6dcf <https://cl.ly/718ec25e6dcf>
<https://cl.ly/718ec25e6dcf>View here: https://cl.ly/718ec25e6dcf <https://cl.ly/718ec25e6dcf>

After the event is published you WILL receive an error message if you attempt to update the event. The error message received Here  <https://cl.ly/93062623166b>is  what we would expect to happen
If an event is published with the start time after the end time Customer's will not have the ability to see their tickets in Upcoming events, instead, they see them is past events one the end time is set.

**Comment by Tas4tari** [comment]
@mikethetike Could you please have a look at this issue.

**Comment by Anziskavds** [comment]
Tested on Develop and Beta and is working as expected

https://cl.ly/a61c47fe5f59

**Comment by Anziskavds** [comment]
Tested on Prod and it working as expected.

https://cl.ly/77e0fa4cc00f
