### ISSUE TITLE
Need more information from the Fan Activity endpoint for Fan Management

### ISSUE THREAD

**Issue by shanimal08** [big-neon/bn-api#1398]
Hi guys, just a few more things, sorry.

Purchases:
- [ ] Need the promo/hold code

Check-ins:
- [ ] Need the amount of tickets checked in, then an array of the tickets.. BUT it looks like you only ever have one coming back at a time can someone please confirm?
- [ ] Need confirmation on the first number listed in the design, I've put in the ticket_instance_id for now, but it looks a lot longer than the number in the design (design looks like it's the order no, but confusing.. sorry)

Refunds: 
- [ ] I have a total_in_cents value, but I need the Per Ticket Fee, please :)

Thanks!!

**Comment by shanimal08** [comment]
Hi @mikethetike, please can you also add "transfer_key" to the transfers for me

**Comment by Anziskavds** [comment]
Tested successful on Beta on web and mobile web.

**Comment by Anziskavds** [comment]
Related to issue #1507 and issue #1509 who tested unsuccessful this issue can't be closed yet.

**Comment by Anziskavds** [comment]
Tested successful on Prod on web and mobile web.
