### ISSUE TITLE
A System Owner should be able to update a fee schedule for an organization

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-api#142]
child of big-neon/docs#25

**Comment by Timo614** [comment]
Grabbing this one.

**Comment by Timo614** [comment]
Just noticed in the linked issue https://github.com/big-neon/bn-api/pull/241

> In terms of #142, I don't think that we should be updating these entities ever, but rather creating new ones each time. If there is no UI for editing fees, then we can actually close both of #141 and #142.

May not be a card we need any longer? Can someone confirm if we'll ever have a UI for editing fees? Also if we need to create new ones each time is there any benefit of doing this?

**Comment by mikethetike** [comment]
Parked until we have more clarity on this

**Comment by zmelamed** [comment]
Rarely will fees need to be updated. Fee updates require contract renegotiations, and we're going to always want records of the fees that previously existed for accounting/auditing purposes.

So, @Timo614 it does make sense to only have new fee creation, rather than "fee updating".
