### ISSUE TITLE
When a item in an order is refunded, still return the original value for display

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#1426]
`/orders/{id}/details`
![Screenshot 2019-07-26 at 09.40.10.png](https://images.zenhubusercontent.com/5ce2547f6eb508477b329ac7/6492b697-1ad2-4905-9fdc-e97fbe74e620)

**Comment by Timo614** [comment]
Closing since this is set via a merged PR from awhile back.
