### ISSUE TITLE
Code and discount required for /orders/{id}/details

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#1428]
- The `code` returned is the name of the applied code, actual code used is what's required in the designs.
 
- The discount value in cents for a code received on each item is also needed. 

![Screenshot 2019-07-29 at 10.25.05.png](https://images.zenhubusercontent.com/5ce2547f6eb508477b329ac7/f1918dce-45c0-4794-aad8-21d6840582fe)

**Comment by mikethetike** [comment]
Code is there but just need the discount

**Comment by Timo614** [comment]
Just noticed it looks like https://github.com/big-neon/bn-api/pull/1425 is adding this so unassigning myself.
