### ISSUE TITLE
Cache the first and last interaction time per user per org

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#1429]
The performance hit of these 2 queries, https://github.com/big-neon/bn-api/blob/7dd36f5940837927033966f5b43b08ba96d2c987/db/src/models/organizations.rs#L707 and https://github.com/big-neon/bn-api/blob/7dd36f5940837927033966f5b43b08ba96d2c987/db/src/models/organizations.rs#L713 is quite immense (on some of the orgs the request times out with lots of fans).

I propose that we create a new table like `organization_interactions` that has the following fields

id | organization_id | user_id | first_interaction | last_interaction | interaction_count | created_at | updated_at
-- | --------------- | ------- | ----------------- | ---------------- | ----------------- | ---------- | ----------
uuid | uuid | uuid | datetime | datetime | integer | datetime | datetime

We could use the domain events or manually hook in to any changes on `orders`, `ticket_instances.redeemed_at`, `transfers`, `event_interest` and update the `organization_interactions` table for that organization for that user.

Doing it this way will bring the query time back down because the join will be extremely simple.

**Comment by Timo614** [comment]
Sorry about that -- didn't realize the impact there with the larger organizations but I should have.

I'll adjust this today to use this setup.

**Comment by Timo614** [comment]
Closing since this is set via a merged PR from awhile back.
