### ISSUE TITLE
Check Fans endpoint - Cancelled Transfer 

### ISSUE THREAD

**Issue by shanimal08** [big-neon/bn-api#1444]
Hi, 

Can someone have a look at this -

One of the user's activity_items Cancelled Transfer had a null value for cancelled_by

https://cl.ly/c46e8ed16ac1

**Comment by Krakaw** [comment]
It is possible that the cancelled_by field was only added after the cancellation occurred. If you do a cancellation now and it populates the cancelled_by field, then we are good to go. (You can close this issue if this is the case)

**Comment by shanimal08** [comment]
Looks like that's exactly what happened. Thanksh!
