### ISSUE TITLE
A user must be able to send an individual ticket to a person via sms

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-api#176]
child of big-neon/docs#21

**Comment by Jasonvdb** [comment]
Using the same endpoint as sending the link via email. The field name is `email` though so if that needs to be changed to something more generic let me know to change bn-web.

**Comment by Jasonvdb** [comment]
The link sent in the email is obviously super long and texts are limited to 160 chars. So some link shortening method/service is needed.

**Comment by Jasonvdb** [comment]
Awesome that looks like what we need

**Comment by Jasonvdb** [comment]
We just need to still be careful that the link isn't short enough to be guessed. If the short link is guessed then they have access to the transfer key and signature to steal the tickets. We can set an expiry time which helps though.

**Comment by zmelamed** [comment]
Yeah, I think between the naturally expiring nature of the transfers and an
11-12 character alpha-numeric like https://youtu.be/MXgLQ8QDXk8 (youtube
uses 11 chars) it'd be reasonably difficult to brute force
