### ISSUE TITLE
An Organization member should be able to look up a users ticket ID to check a User into an event

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-api#185]
child of big-neon/docs#20

**Comment by Timo614** [comment]
Just a note: we don't have a check-in method yet but we do have a lookup by ID method (via #336):
https://github.com/big-neon/bn-api/blob/master/api/src/controllers/tickets.rs#L30

Not sure if this card is just for the lookup by ID and if we're handling the check in method in another issue.
