### ISSUE TITLE
An Organization member should be able to view ticket and user details after scanning a tickets QR code

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-api#186]
child of big-neon/docs#20

**Comment by philipr-za** [comment]
@Jasonvdb Is this something that is solved in the front-end using the info from the /tickets/{id} get endpoint response?

**Comment by Jasonvdb** [comment]
@philipr-za yeah if the endpoint can provide the text field needed in the QR code. Not sure what that's supposed to be at this stage?

**Comment by philipr-za** [comment]
After discussion with @mikethetike we decide we will include the Ticket ID and the Redeem Key in the QR code. The redeem key will be generated and exposed in the PRs Mike and I are putting in today.
