### ISSUE TITLE
A User should be able to update their profile picture

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-api#192]
child of big-neon/docs#24

**Comment by Jasonvdb** [comment]
Implemented in bn-web already. 

Sending through `profile_pic_url` when updating profile details when doing a PUT `/users/me`

**Comment by Jasonvdb** [comment]
Thumbnail can be something like `thumb_profile_pic_url`

**Comment by Timo614** [comment]
Grabbing.
