### ISSUE TITLE
An Organization Admin and Organization User should be able to integrate with their SendGrid email list where customer information will be sent to

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-api#194]
child of big-neon/docs#18
Requires #537

**Comment by Krakaw** [comment]
@zmelamed for MVP this could possibly be an export to CSV so that the users can use their own implementations of MailChimp / SendGrid / Whatever email system

**Comment by zmelamed** [comment]
There would be two things needed to make this work for MVP:
1) Org Admins can add a sendgrid API key to the account (a string)
2) If they have a sendgrid API key, on ticket purchase we add a single contact to their account through the API (first name, last name, email) https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#Add-Single-Recipient-POST

The users will be using their own sendgrid accounts, not ours.

We can do this manually for them if need be, so we'll want at least a CSV export function on the fans list and we can punt the posting of emails to shortly after launch. 

We'll want to have the ability to add a sendgrid API key to a orgs account though day one. This can just be a single input form under the marketing section.
