### ISSUE TITLE
Allow for creating an event with all missing fields

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#213]
Make all fields optional so a user can create a draft event to edit or add artists later. 

All fields can be null except for `status`

**Comment by Timo614** [comment]
I'll grab this one.

**Comment by Timo614** [comment]
Just confirming: you want the name field to still be required right? Or that should be optional at first as well?

**Comment by Timo614** [comment]
Pushed up a PR with `name` and `organization_id` required but the others optional. Let me know if I should adjust.
