### ISSUE TITLE
Adding artists to events should be done via typeahead search

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-api#219]
child of big-neon/docs#15

When an event is created, the artist field should be a typeahead search for the Artist rather than a dropdown, as not all Artists will be present in the system. 
If the artist is not available the event creator can Choose "Create a new artist [Artist Name]" from the typeahead results that appear. 
When the event is saved, the artist should be saved to the artists DB and associated in the artist DB with that organization so that we can restrict the use, and management of that specific artist to that organization. Eventually the System Owner can decide if they want the artist to be globally accessible.

**Comment by Jasonvdb** [comment]
For now typeahead is just a bn-web that's been merged already. Discussion: https://github.com/big-neon/bn-web/issues/152

Created a new issue for discussing the linking an artist to orgs: https://github.com/big-neon/bn-api/issues/222
