### ISSUE TITLE
Link artists to organizations

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#222]
When an org member/owner adds an artist it needs to be initially linked to that org and viewable for that org. There should be an option to make that artist globally accessible later.

Not sure what api/db changes are required but maybe we can push this one out till later.

**Comment by Timo614** [comment]
I think this one may be set now.

In the lockdown branch the venue / artists create and update were modified a bit for the purposes of preventing unauthorized access.

Now the logic works such that:
- An organization create that does not specify an `organization_id` returns unauthorized for all but admins
- An organization create that does specify an `organization_id` but the current user lacks `ArtistWrite` permissions for the organization (isn't part of it or just has a role which doesn't have access to it) an unauthorized status is returned
- An organization create that does specify an `organization_id` and the current user has `ArtistWrite` permissions for the org creates the artist with it tied to the organization and it's initially set to private
- Organization users with `ArtistWrite` permission can edit that artist so long as it hasn't been toggled to public (which returns unauthorized for all but Admins who may still edit it)
- Admins now have an endpoint to toggle privacy on the artists and venues
