### ISSUE TITLE
Refactor DB connections into DbExecutor pattern

### ISSUE THREAD

**Issue by mikethetike** [big-neon/bn-api#25]
We need to investigate whether this is a better pattern to use for connection pooling: https://actix.rs/docs/databases/

We must keep in mind the ability to test against a test database in the `bn-db` project.

**Comment by mikethetike** [comment]
Also, need to verify that transactions are being used in the controllers

**Comment by Timo614** [comment]
I've been looking into switching the tests to the integration test logic after I spent some additional time trying to reintroduce the path logic to no avail.

I was working on this branch as part of changes to try to get integration tests working as I was running into errors with our db approach and converting it (given the hacky nature of what we need to do now to get those to work seemed worth it).

I ended up spending quite a bit of time trying to convert the middleware to a future (still getting the hang of some of the finer points of ownership and the futures logic forced me to spend a bit of time trying to wrap my head around it) and converted the artists and auth controllers to the other approach just to get a feel for it.

https://github.com/big-neon/bn-api/commit/898868ef5b1d2ffa60dd6a75a04abeaf6a3070c0

I don't think it's worth doing. It adds a ton of code and abstractions which just make it harder to follow the code and we end up having to do a lot of boilerplate to even do simple things like find a user.

I'm not really sure if there's a good way around that. The approach even forces wrapping the parameters with a struct as you can't implement a trait for a struct when both are not part of your crate (bn-db).

In general I was going to continue working on this now that I got past those blockers but I think it's a waste of time and I've probably already wasted too much trying to even get this part working (I should have probably given up when I realized how much extra code it forces but was originally hoping I could find a way to refactor it once I get it working). Not really feeling like I can improve it much though beyond this.

Sorry for the waste of effort there -- I'll keep the branch around in case we decide this is worth it but from my experience with it so far I don't think we'll gain much we'll just confuse developers contributing and waste a lot of effort working around the limitations of this abstraction.
