### ISSUE TITLE
Captcha on Login

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#259]
If there is a GOOGLE_API_KEY .env then implement recaptcha, otherwise we can implement other options at a later date.

No rate limiting on login (low risk) - this ability to brute-force, chained with the weak password requirements, would leave user accounts open to the taking. The easiest fix is to lock an account after N number of incorrect attempts for N seconds and gradually increase the time. The slightly harder would be like a capture

Child of big-neon/docs#28
Blocked by big-neon/bigneon#20

**Comment by Timo614** [comment]
Grabbing
