### ISSUE TITLE
A user needs to be able to remove an item from their cart

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#294]
Something long the lines of a delete request at `/cart` and passing through a ticket type id to delete.

**Comment by Timo614** [comment]
Sounds good.

@Jasonvdb I'll have an optional quantity field so if it's not present we remove the entire ticket type id otherwise we remove up to that number of tickets specified.

Should we also add an endpoint to clear the cart completely?

**Comment by Jasonvdb** [comment]
Great thanks @Timo614. You can add an optional quantity but I think the UI might just have one remove button that removes the whole line. So all tickets for that ticket type. But go ahead and add it if it's not a lot of work and you think it might be used later though.

**Comment by Jasonvdb** [comment]
Actually giving it a second thought, we'll need to have an option to go back and update ticket quantities, adding some or removing some after they've reserved them. Is that what you're thinking adding the quantity field would be for?
