### ISSUE TITLE
Refactor the management of fee schedules

### ISSUE THREAD

**Issue by philipr-za** [big-neon/bn-api#300]
We need to rethink the structure of managing fee schedules.

The user stories describe fee schedules be created per organization but currently fee schedules are created globally and linked to from the organization table. This led to a lot of validation to make sure an organization has a valid fee schedule when it issued assets for sale (i.e. tickets but later merch etc).

My proposal for this refactor:
- Remove fee_schedule_id from organizations table
- Add organization_id to fee_schedules table
- Add validation to ensure there is a valid fee schedule when an asset is issued for sale. I don't think we can get away from this validation as there might be a fee schedule but what if it doesn't cater for a given price point? There will need to be an error in any case.

**Comment by Krakaw** [comment]
Fee schedules have changed since these days, the fee schedules are currently working. We will open a new issue when merch etc gets sold if there is a need to change the fee schedule.
