### ISSUE TITLE
/venues returns empty array

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#302]
If I'm the owner of an org I can't seem to get any results for venues after adding one to my org.

Seems like it might only be showing you results if you're a member and not an owner.

This was working previously, not sure if it's related to https://github.com/big-neon/bn-api/pull/273

**Comment by Timo614** [comment]
Looks like it's related to https://github.com/big-neon/bn-api/blob/master/db/src/models/venues.rs#L120 the logic there needs to check if the user in question is the owner as it's only checking if the user is a member and there's no organization user record for the owner.

In #273 new venues created by an organization member or owner are locked down to just ones associated with them and they're made private right away for those users. Previously they were never private but always public so it didn't trigger that logic.

I'll file a patch for it quickly should be a simple change there to have the query check if the user id is equal to the owner id as an alternative to the filter checking against the organization users join.
