### ISSUE TITLE
If the user over pays, add the remainder to his account

### ISSUE THREAD

**Issue by mikethetike** [big-neon/bn-api#317]

**Comment by mikethetike** [comment]
@zmelamed Is this what should happen if the user for some reason pays too much for an order?

**Comment by zmelamed** [comment]
@mikethetike There should be a function to refund a payment. But I'm not really clear on in what case an over payment would/could ever happen?

**Comment by Krakaw** [comment]
The main time when this would happen is when paying via crypto. This was closed in big-neon/bn-api#1189
