### ISSUE TITLE
Extend cart expiry time when user attempts to pay

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#342]
We don't want users getting cut off as they submit their credit card details if stripe takes a while to process. 

A possible solution would be an endpoint to be used to extend the time by a minute or 2 when bn-web is retrieving a stripe token.

A little dodgy to do though if a user figures it out and keeps extending their cart time. Maybe we only allow an expiry time to be extended once per cart?

**Comment by mikethetike** [comment]
Perhaps we can set the status to PendingPayment (perhaps AwaitingPaymentConfirmation?) that only expires after a few days. It opens us up to certain other problems, but I think that we will avoid the main problem of selling a ticket twice, and then having to work out who has the ticket

**Comment by Jasonvdb** [comment]
I'm happy. But we still need someway to empty the cart if it expires. Will get the expiry time now to display to a user so we can communicate that with them. But I think right now they just stuck with a cart they can't use.

**Comment by philipr-za** [comment]
I actually made a bug issue about that problem https://github.com/big-neon/bn-api/issues/356
