### ISSUE TITLE
'event_past' flag needed for /tickets endpoint.

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#363]
bn-web needs to show display separate tickets to the user for events that are upcoming and ones that are past.

**Comment by Timo614** [comment]
The tickets endpoint takes optional `start_utc` and `end_utc` parameters so should be able to use the `end_utc` of the current date time and see the ones from the past and `start_utc` of the current date time to see the future ones. We could take a flag in place of that but figured this approach offered more customization for display purposes.

**Comment by Jasonvdb** [comment]
Ok great thanks will use that then.
