### ISSUE TITLE
Change 'flat fee' to 'per event fee'

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#429]

**Comment by Timo614** [comment]
I couldn't find any uses of flat fee in the code for bn-api or bn-api-node -- is this a bn-web issue? Did find it used here:
https://github.com/big-neon/bn-web/blob/4b4d36e5eef939ef9261e68b285b0f3336750847/src/components/pages/admin/organizations/cards/UpdateCard.js#L360

https://github.com/big-neon/bn-api/search?q=flat+fee&unscoped_q=flat+fee
https://github.com/big-neon/bn-api-node/search?q=flat+fee&unscoped_q=flat+fee
https://github.com/big-neon/bn-web/search?q=flat+fee&unscoped_q=flat+fee

It looks like in bn-api we call it `event_fee_in_cents`.

**Comment by Jasonvdb** [comment]
Sorry @Timo614, this was mentioned briefly while in the demo so I quickly made the issue. I assumed they were talking about the description of the order item that gets added and shown to the user when viewing their cart. But they must have been talking about the admin section input in bn-web.
