### ISSUE TITLE
Missing top_line_info from event get request

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#431]
I see the field is being saved here https://github.com/big-neon/bn-api/pull/395

But it's missing from the get endpoint for displaying it:
`/events/{id}`

**Comment by Timo614** [comment]
Sorry about that, I did the same when I added the increment field as well recently (forgetting to add it to the display ticket type originally but caught myself soon after and made a second PR) -- I'll keep a closer eye on that aspect of surfacing it for the frontend with these going forward.
