### ISSUE TITLE
Price at door for ticket types

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#504]
The designs have a `price at door` inout when creating ticket types. Not sure what the plan to accommodate this is? Set per ticket type or an additional ticket_pricing?

**Comment by mikethetike** [comment]
@Krakaw any ideas on this? I first thought about creating a new ticket pricing, but then you would have to link the two together in order to display it

**Comment by mikethetike** [comment]
Unless we have a single ticket pricing that has type "Price at door"

**Comment by Krakaw** [comment]
Could we not just make that the a TicketPricing object with a predefined name of "Price At Door" and the start and end dates the day of the event.

Then maybe to differentiate it we can have a flag for on-site price so it doesn't show up for the online items. Is this going to mess with our database validation rules of having no 2 ticket_pricing row dates overlapping?

**Comment by mikethetike** [comment]
Cool. Happy with that

>Is this going to mess with our database validation rules of having no 2 ticket_pricing row dates overlapping?

We can work around this

**Comment by Krakaw** [comment]
@zmelamed We're going to go with a `price_at_door` boolean for the ticket_pricing, which will only be available to box office event members

**Comment by Krakaw** [comment]
Going with `is_box_office_only` to allow the ability to create internal tickets that can be sold at any overlapping date but only by the in-house users that have the correct permission.

**Comment by Jasonvdb** [comment]
@Krakaw when bn-web sets a `price_at_door` field, does bn-api create that extra ticket type?

**Comment by Krakaw** [comment]
@Jasonvdb the logic will happen on the client side, if they create a `price_at_door` the frontend will add another `ticket_pricing` element that has the `is_box_office_only` flag set to true.
