### ISSUE TITLE
Need a `liveness` endpoint that can be tested to ensure the app is up

### ISSUE THREAD

**Issue by sdbondi** [big-neon/bn-api#514]
We need some method of telling if the application is up and running. 

This can be implemented by creating an endpoint (`/healthz` is a common standard, `/liveness` also good).  All the endpoint needs to do is to return an `http 200` response.

I can take this since it's an easy one

**Comment by Krakaw** [comment]
There is a /status endpoint that returns 200

**Comment by sdbondi** [comment]
@Krakaw Ah thanks should have searched for status in routes
