### ISSUE TITLE
Can't delete holds

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#534]
`"BigNeonError(DatabaseError { code: 7200, message: "Validation failed:", cause: Some("ValidationErrors({\"quantity\": Field([ValidationError { code: \"assigned_comp_count_greater_than_quantity\", message: None, params: {} }])})"), error_code: ValidationError { errors: {"quantity": [ValidationError { code: "assigned_comp_count_greater_than_quantity", message: None, params: {} }]} } })`

**Comment by Timo614** [comment]
I believe #538 fixes this if you can try in that branch. Deletes the associated comps when a hold is deleted (assuming none are already assigned to order items as that triggers a validation error).
