### ISSUE TITLE
Test user scopes / roles / contexts

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#541]
Testing org creation, venue creation and org activities are properly limited for different user roles / scopes.

**Comment by Timo614** [comment]
We do have some tests already for these endpoints. What's missing for this one?

We have organization create tests for each role (along with the other activities):
https://github.com/big-neon/bn-api/blob/master/api/tests/functional/organizations.rs#L68

Also for each venue (which confirms that organizations can only make venues for their own organization but admins can make public organizationless venues regardless):
https://github.com/big-neon/bn-api/blob/master/api/tests/functional/venues.rs#L142
