### ISSUE TITLE
Extra fields required in GET /organizations/{id}/events

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#542]
@jasonvdb please add the fields you require

**Comment by Jasonvdb** [comment]
@Krakaw is this issue not maybe meant for `/organizations/{id}/events`?

This admin view of events we chatted about on Friday: https://share.goabstract.com/aa9973dd-d3e9-4c46-b468-8308fef2eeaa

**Comment by Jasonvdb** [comment]
- Venue name (Maybe include the whole venue object)
published
- on sale
- sold count
- open count
- held count
- capacity
- sales ($)

**Comment by Jasonvdb** [comment]
I see there's an option to expand cards to view ticket type summaries. 

So will also need these for each ticket type:
- Sold count
- Open count
- Held count
