### ISSUE TITLE
Create event view fields for admin

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#544]
GET /organizations/{id}/events/{id}
@jasonvdb needs extra fields for bn-web
https://app.goabstract.com/projects/20f4bd60-ab00-11e8-b694-6fcb86ba37e4/branches/master/collections/78dec09d-bd7a-4539-9163-cad557673a91/layers/45bb0766-34b1-4400-9de3-da6372efdaeb/presentation

**Comment by Jasonvdb** [comment]
Have built the layout, can just plugin the data when it's ready.

For the top chart maybe we need a separate API call that accepts a date range or just a single month to return stats for.

The dummy data I'm working with looks like this:

```
[
  { day: 1, ticketSales: 99, revenue_in_cents: 3000 },
  { day: 2, ticketSales: 120, revenue_in_cents: 4000 }
];
```
