### ISSUE TITLE
Panic when making an API call with an invalid token.

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#55]
Happens when an API call is made with an invalid or missing token.

Validating on the frontend so it doesn't happen for the web but could affect other apps using the API at a later stage.

`api_1   | thread 'arbiter:"3393fd3b-c1f4-45c6-b6d2-235aa4d8e9d2":"actor"' panicked at 'called 'Result::unwrap()' on an `Err` value: Utf8(FromUtf8Error { bytes: [158, 233, 101], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } })', libcore/result.rs:945:5
`

`api_1   | note: Run with `RUST_BACKTRACE=1` for a backtrace.`

**Comment by Timo614** [comment]
Grabbing this one.
