### ISSUE TITLE
BUG: Add User auth check for events::show_from_organizations() in api

### ISSUE THREAD

**Issue by mikethetike** [big-neon/bn-api#558]

**Comment by Timo614** [comment]
@mikethetike were you thinking of making the User an optional parameter here and it'd gate whether to show `Draft` events or not? 

Or did we want to lock this down to just organization members?

**Comment by Timo614** [comment]
Looks like #568 added this.

**Comment by Timo614** [comment]
This can be closed #568 added it:

https://github.com/big-neon/bn-api/blob/master/api/src/controllers/events.rs#L532..L542
