### ISSUE TITLE
Add ticket price to /tickets

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#573]
Required for fan hub:
https://share.goabstract.com/f749c848-8881-40b6-8f3d-d6bca687d0e0

**Comment by Timo614** [comment]
Just confirming, we want the actual price not what the user paid for them (ie: with discounts, hold discounts, or comps).

**Comment by Jasonvdb** [comment]
@zmelamed can you confirm the price shown on their tickets is the paid price?

**Comment by zmelamed** [comment]
Yes confirmed, it should be the price paid for the ticket

**Comment by Timo614** [comment]
Sounds good, will reopen this and quickly modify it to use that instead of the current price on the endpoint.

**Comment by Timo614** [comment]
@zmelamed fee inclusive in the price right? Or just the ticket price with discount applied?

It shouldn't include its portion of the event fee right? Or should it with event fee / ticket number?

**Comment by zmelamed** [comment]
per ticket fee inclusive, not event fee.

**Comment by Jasonvdb** [comment]
@Timo614 the guest ticket list also requires order_id and price_in_cents. I created a separate issue for it here: https://github.com/big-neon/bn-api/issues/641
Not sure if it related these functions are.
