### ISSUE TITLE
Add SPOTIFY_AUTH_TOKEN to .travis.yml

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#578]
Blocked by #577

**Comment by Krakaw** [comment]
@zmelamed We need a Travis account for BigNeon

**Comment by Krakaw** [comment]
@sdbondi Where is the script to create the encrypted vars?

**Comment by sdbondi** [comment]
@Krakaw In `scripts/encrypt-travis-env.sh`- you put a .env in `.travis/.env` and it will encrypt all the vars and add them to the `.travis.yml` file
