### ISSUE TITLE
Organizations/events endpoints too open

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-api#58]
We're forcing a OrgMember role to access the endpoints but we're not filtering the data down to those that the given user has access to.

https://github.com/big-neon/bn-api/blob/master/src/controllers/organizations.rs#L30

Just need something in the logic first to confirm the user can access the resource to edit as they may not be the org owner or member of that given org.

The events one has this issue via the organization_id in the new event and update events:
https://github.com/big-neon/bn-api/blob/master/src/controllers/events.rs#L69
https://github.com/big-neon/bn-db/blob/master/src/models/events.rs#L30

Could allow another org owner who doesn't belong to the organization to assign events to it. May be others just quickly saw those when looking through.

**Comment by mikethetike** [comment]
Let's investigate Venues as well

**Comment by mikethetike** [comment]
It might be an idea to return 401 when the user does not have the correct role/scope to perform the action, and 403 when they do have the role but don't have access to that entity (e.g. someone else's organization)

**Comment by Timo614** [comment]
Grabbing.

Sounds good I'll use 403 (Forbidden) if the user is authenticated but lacks access and I'll adjust the controller actions to all properly confirm their access.

**Comment by Timo614** [comment]
@zmelamed a few quick questions:

- What level of access should be able to create an organization private artist? We currently allow org members to create events, should org members be able to create private artists? Or just the org owner?
- If you have the OrgOwner role should you be able to lookup any user in the system? That's how it is now but wondering if we should lock it down to just members of the given user's organization. I guess it depends on how those endpoints are used and locking it down would prevent an organization from being able to search up a given user to add to their org. I'm just concerned about the privacy implications of giving the org owners full access to random user data via the lookups.
- Do we plan on supporting multiple OrgOwners in the future? The current scope setup doesn't work really well with that so we'd have to likely have some sort of role associated with the organization_users table so we can confirm that the user has the role for the given organization (otherwise if they were granted OrgOwner status then they'd have it across all of their organizations given the scope setup we've been using).

**Comment by zmelamed** [comment]
- Any member that can create an event can create the artist for an event, not just the OrgOwner

- Orgs should only be able to view users and users activity related to that org and that orgs events. In regards to adding an OrgMember to an org: An org should be able to add a user as a member of their org by email invite, not by selecting them from a public global pool of users.

- a single org owner, yes, but there will be the need for multiple org admins https://github.com/big-neon/docs/blob/master/overview.md

**Comment by Timo614** [comment]
>  - Orgs should only be able to view users and users activity related to that org and that orgs events. In regards to adding an OrgMember to an org: An org should be able to add a user as a member of their org by email invite, not by selecting them from a public global pool of users.

Sounds good, I'll lock those user endpoints down.

> - a single org owner, yes, but there will be the need for multiple org admins https://github.com/big-neon/docs/blob/master/overview

Sounds good, I'll make sure to file a follow up issue for us to add that capability as right now just associating the role with the user won't be a good enough way to lock it down (as users can be part of multiple orgs). I'll encapsulate the logic for determining if the user has that org level access (for the purpose of locking it down) so it's easy for us to support multiple admins once we have that functionality in place.
