### ISSUE TITLE
Panic when trying to replace items in a cart

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#586]

**Comment by Jasonvdb** [comment]
/events/{id}/tickets

```
{ "level": "DEBUG", "target": "logging", "message": "Found an existing cart item, replacing" }
{ "level": "DEBUG", "target": "logging", "message": "Found an existing cart item, replacing" }
thread 'arbiter:4100498e-dd4c-43af-be9c-04d5a70a1f14:actix-net-worker-7' panicked at 'assertion failed: index < len', liballoc/vec.rs:888:9
```

**Comment by Jasonvdb** [comment]
Happened when I loaded existing cart items in the selecting tickets for so users can go back and edit their cart contents. First time adding items works, updating seems to fail. Not sure if maybe I'm calling it wrong somehow.

**Comment by philipr-za** [comment]
Tested this as follows:

1. Added tickets to cart calling PUT /cart with:
{
"items": [{
"ticket_type_id": "{{ga_ticket_type_id}}",
"quantity":2
}, {
"ticket_type_id": "{{vip_ticket_type_id}}",
"quantity":7
}]}

2. Viewed the cart and then replaced some of the tickets calling PUT /cart with:
{
"items": [{
"ticket_type_id": "{{vip_ticket_type_id}}",
"quantity":4
}]}

3. repeated that process a few times (view cart, replace tickets).

No errors.

I think this issue has been fixed so closing.

**Comment by philipr-za** [comment]
I reproduced this when you try replace items in the cart but go over the per user ticket limit
