### ISSUE TITLE
Standardise on min_ticket_price and max_ticket_price for endpoint /venues/{id}/events

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#599]
Already returned in `/venues/{id}/events`
But seems to be missing in `/events`

**Comment by Jasonvdb** [comment]
Sorry I see it exists in both but the venue events endpoint returns it as `max_ticket_price_cache` while the event endpoint returns it as `max_ticket_price`.
Any reason for this or can we standardise?

**Comment by Krakaw** [comment]
No reason, this is a bug, it should be standardised on `min_ticket_price` and `max_ticket_price`

**Comment by Jasonvdb** [comment]
Cool thanks, changed the title then
