### ISSUE TITLE
Need order_id and price_in_cents for endpoint /events/{id}/guests

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#641]
Design requires these 2 fields: https://share.goabstract.com/f13f2b1e-50cb-43db-8f1f-ed2fb53dbfc0

**Comment by Timo614** [comment]
Sorry about that, added it to the user's tickets endpoint but the admin section redeem endpoint is handled a bit differently as it has its own return set and didn't think to add it there. Will quickly add these two values to it.

**Comment by Jasonvdb** [comment]
No worries, thanks! Only noticing whats missing myself as I'm implementing it
