### ISSUE TITLE
Org Invites & Roles

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-api#701]
- [ ] As an org owner or Org Admin I should be to add people to my org by providing their email address and an access level. 
  - This should send an invite to the email address so that person can accept that invite.
  - As a user accepting an invite I should be presented with a modal to confirm that I’d like to join the org, if confirmed I should be routed to studio for that org
- [ ] There should be at least the following access roles for a user. 
	1) Org Owner - Can manage team (including adding admins), view all reports, update org details, create events, manage tickets, manage holds, sell tickets through box office, check people into events
	2) Org Admin - Can manage team (cannot add other admins), view all reports, update org details, create events, manage tickets, manage holds, sell tickets through box office, check people into events
	3) Org Member -  View Events List/Dashboard, View all reports without fees, create events, manage tickets, manage holds, sell tickets through box office, check people into events
	4) Box Office -  View Events List/Event Dashboard, view orders, view tickets, view holds, sell tickets through box office, check people into events
	5) Doorperson -  View Events List, view holds, check people into events
- [ ] As an org owner or Org Admin I should be able to modify an org members access level.

**Comment by Jasonvdb** [comment]
@Krakaw @mikethetike I'm working on the bn-web interface for this but please checkout https://github.com/big-neon/bn-api/issues/702 and https://github.com/big-neon/bn-api/issues/703 that I need to make it work.
Those are pretty important but in the meantime I'll test by manually updating the DB.

**Comment by Jasonvdb** [comment]
@Krakaw @mikethetike we don't have an Org Admin role?
