### ISSUE TITLE
Status 500 when signup with existing email address

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#71]
If a user accidentally tries to sign up again by accident then it should maybe return 400 instead if 500 and a message saying that the user already exists. 

Related to #66 

`Error occured during request handling, status: 500 Internal Server Error Could not insert record`

**Comment by mikethetike** [comment]
@Jasonvdb I believe this has been fixed....

**Comment by Jasonvdb** [comment]
Ya seems to fixed. 409 now. 
Still need those user friendly messages I think

**Comment by mikethetike** [comment]
yeah 409 CONFLICT is returned if the email already exists.
