### ISSUE TITLE
Add missing roles

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-api#711]
Related to #701

Need to add additional roles to the organizations and adjust functional tests to take them into account.

Org Owner - Can manage team (including adding admins), view all reports, update org details, create events, manage tickets, manage holds, sell tickets through box office, check people into events
Org Admin - Can manage team (cannot add other admins), view all reports, update org details, create events, manage tickets, manage holds, sell tickets through box office, check people into events
Org Member - View Events List/Dashboard, View all reports without fees, create events, manage tickets, manage holds, sell tickets through box office, check people into events
Box Office - View Events List/Event Dashboard, view orders, view tickets, view holds, sell tickets through box office, check people into events
Doorperson - View Events List, view holds, check people into events

**Comment by Krakaw** [comment]
@mikethetike is redoing roles

**Comment by Timo614** [comment]
Gotcha, will reassign this his way.

**Comment by mikethetike** [comment]
I think I have done most of these. Might be worth someone doing a review to make sure that they are correct

**Comment by Timo614** [comment]
Will do a review of these today.
