### ISSUE TITLE
When admin adds a new venue/organization it's not saving all details

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#75]
Passing below params to `/venues` but it only seems to be saving the `name` field

`
{
"name":"Jazz Hands Bar",
"organization_id":"14484360-f049-44d9-bca1-9824f70eb088",
"phone":"0897373833",
"address":"10 2nd Avenue, New York, NY, USA",
"city":"New York",
"state":"New York",
"country":"United States",
"zip":"10003",
"place_id":"ChIJgdinUYRZwokR06E7yqMzm5Y"
}
`

Not sure if I'm maybe calling it incorrectly.

**Comment by Jasonvdb** [comment]
I'm creating the entry and then updating it right away from the frontend with the rest of the details. This works but it would be better for it to be able to save all the details in one API call in the future.

**Comment by Jasonvdb** [comment]
I'm creating the entry and then updating it right away from the frontend with the rest of the details. This works but it would be better for it to be able to save all the details in one API call in the future.

**Comment by Jasonvdb** [comment]
Same happening when creating an hitting `/organizations`

**Comment by philipr-za** [comment]
This was fixed in https://github.com/big-neon/bn-db/pull/55
