### ISSUE TITLE
Declining invites are failing

### ISSUE THREAD

**Issue by neonknight64** [big-neon/bn-api#754]

**Comment by Timo614** [comment]
I'll take a look. The odd thing about this is there's nothing in the decline_request method that would trigger "User does not have the required permissions."

That message is only triggered by the requires_scope logic or an explicit `application::unauthorized` method call. The method does take an unused `OptionalUser` so it could error out if the user is logged in and passes an invalid token though but that isn't the case here as you mentioned they are logged out and that would also trigger a generic 401 even if it did trigger not with that additional text.

I'll file a PR today to remove these unused user objects as they have no value and do some additional bn-api testing.

**Comment by zmelamed** [comment]
Honestly I don't think we need a decline invite method, I don't think I've ever seen a saas app where an invite has a decline button, the invite just gets ignored.
