### ISSUE TITLE
Cors issue when calling 

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#77]
Preflight failing when posting to `/external/facebook/web_login`.
`No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Other endpoints working fine though. @mikethetike any idea why just this one doesn't work? 
Used branch `mikethetike-fb-login` to test.

**Comment by mikethetike** [comment]
@Jasonvdb is this still happening?

**Comment by Jasonvdb** [comment]
Nope all good thanks. Was docker not updating to the latest commit. Compiling api directly.
