### ISSUE TITLE
Order Support - Refunds - A org member should be able to refund ticket purchases

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-api#785]
An org member should be able to view the order details page for any order.

The order detail page should show a table (similar to the table in the box office guest list view) listing each ticket in that order (with fees, face value, and total price listed for each ticket) and should also have any event fee that was paid if applicable.

The org member should be able to select all or just one of the table items which will enable a Refund button.

After clicking refund button, the org member should be prompted to confirm the refund and  should receive an email that the order was refunded, and the items refunded should still appear in that order detail list, but there should be a label indicated that the item was refunded.

**Comment by Timo614** [comment]
I've been working on this one for a little bit hoping to wrap it up next week. I've run into a few scenarios I was hoping to clarify though @zmelamed if you have a chance:

- Should comps be allowed to be refunded to put them back in the available list? Or only allow refunds on paid orders?
- Are there any situations where we should cutoff when refunds are allowed? Or can a purchased and redeemed ticket be refunded?
- Normally tickets are returned to available inventory after refunding right? Or should that be an option as part of the refund to allow refunded but still existing refunds?
- Transferred tickets are not eligible for any refunds right? (I assume so as the person ordering no longer has access).
- Should fees be recalculated given the pricing will be different? What if the lower item quantity ends up having higher fees? Should we only refund part of the ticket price and then modify the fee order item to reflect the new fee? It may get a bit confusing.
- Not really a problem for the MVP as it's only a mockchain for now but we'll likely need to make refunds contingent on the wallet having and transferring out the tickets back to our organization wallet right?
- Event fees are automatically removed if there are no existing tickets left for the event right? (I'm assuming such with the code at the moment but confirming here).

**Comment by zmelamed** [comment]
@Timo614, this is so helpful, I really appreciate this

- Should comps be allowed to be refunded to put them back in the available list? Or only allow refunds on paid orders?
  - A refund of a comp should be possible, and would just reverse the comp order if that makes sense
- Are there any situations where we should cutoff when refunds are allowed? Or can a purchased and redeemed ticket be refunded?
  - Purchased and redeemed tickets can be refunded
- Normally tickets are returned to available inventory after refunding right? Or should that be an option as part of the refund whether to allow the user to keep the ticket?
  - I've posed this question to the business team but for now assume the ticket will go back to inventory after refunding.
- Transferred tickets are not eligible for any refunds right? (I assume so as the person ordering no longer has access).
  - Correct
- Should fees be recalculated given the pricing will be different? What if the lower item quantity ends up having higher fees? Should we only refund part of the ticket price and then modify the fee order item to reflect the new fee? It may get a bit confusing.
  - The fees are a per ticket fee, so if the full order is refunded all associated fees would be refunded. If a single ticket from the group is refunded, just the fee for that item would be refunded but the rest of the order would remain the same.
- When a ticket is refunded its portion of the fees should be refunded as well right? So if there are 3 tickets it shows 1/3 of the fees pricing in the listing and once its refunded its 1/3 is refunded as well.
  - Correct, If a partial refund is created for a single ticket, the associated fee with that ticket should also be refunded. 
- Not really a problem for the MVP as it's only a mockchain for now and we control all of the wallets but we'll likely need to make refunds contingent on the wallet having and transferring out the tickets back to our organization wallet right?
  - Yes we'll need to dig deep into this, but not to worry ourselves with it now
- Event fees are automatically removed if all of the tickets have been refunded for the event right? (I'm assuming such with the code at the moment but confirming here).
  - Correct (event fees are actually "Per Order Fees", so if the full order is refunded the per order/event fee should also be refunded)
- Is there a use case for partial payments? Wondering if it makes sense to just remove that logic here as well in favor of always paying the exact amount for an order. It adds some complication as I need to loop over the payments and then refund them up to the total refund. I assume if we do need it I should refund first from any user initiated payment (Stripe) prior to any external payment (in person box office).
  - The partial order amounts should always be equal to some multiple of the ticket+fee. A refund issuer can select 1 of 3 tickets and fees to refund. Refunds would always be in the context of a specific order, an order will always be paid through a single payment method, so the refund should be returned through the same method.
- Based on the description I'm assuming that there are only two things which can be refunded: 1) event fees, 2) individual tickets (which refunds their fees and ticket price itself). Is that correct? Or should only tickets be refundable and the event fee is refunded once none exist any more? Individual ticket fees can't be refunded on their own right?
  - To start we should be fine with just 1 and 2 as you mentioned. I have seen on other platforms the ability to select specific individual ticket fees to refund independently of the tickets themselves, so we may extend it to do that, though we haven't been specifically asked to deliver on that use case yet. Worth keeping in mind though so we can remain flexible in the future
- Since an order can have multiple tickets across different events / organizations should the order details include only the details for ones applicable to the given user? Or list them all but have a flag if the user is capable of refunding them so we can toggle on/off the checkboxes for selection?
  - This is a great catch. I had actually pressed to avoid multiple event ticket purchases in a single order because I sensed we'd hit some weeds here. It should only show the order details for the org belonging to that specific user, and should probably have a flag letting the user know that the order contains tickets for other organizations and not allowing entire order refunds.
- Like above, if the current user does not have refund capability for the given organization that owns the event some tickets belong to they should not be able to refund those right? So the user will need to speak to two different organizations if they wish to refund their entire purchase?
  - They'd need to inform the user that they will need to contact the ticketing platform to refund the portion of the order for which they are not allowed to modify.
- Outside of scope here but how will organizations know they are needed to refund part of an order? Is there going to be an escalation process from support that asks each organization to perform their half of the refund if a user wanted to refund an entire order with different events?
  - Yes there will need to be an escalation process that reaches us (Big Neon), this will be done through a support channel and we'll need to educate the users of how to handle this.
