### ISSUE TITLE
Marketing - Email Integration - If account has sendgrid key, every purchasers email and name should be automatically pushed to a sendgrid contact list tagged with the event name they purchased for

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-api#805]

**Comment by sdbondi** [comment]
@zmelamed few questions:

1. Should the user be able to specify a contact list id that fans should be added to or should we create a 'big neon' list for them?

2. If a sendgrid key is added later should we bulk import existing fans?

**Comment by zmelamed** [comment]
Sorry for the late response here, all of your assumptions are correct. Thank you
