### ISSUE TITLE
Ticket Transfers - Transfer tickets behaving odd "Business process error"

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#847]

**Comment by Krakaw** [comment]
@Jasonvdb what was the process to generate the error?

**Comment by Jasonvdb** [comment]
Used the link and login details from the comment above

**Comment by Jasonvdb** [comment]
Managed to replicate this once internally, first transfer I did worked. Then when I tried another, got the `Business process error`.

Can't see anything wrong with the payload:

```{"transfer_key":"a25ccbd6-6c9b-4422-ae7f-72a73d2536e6","sender_user_id":"89dbfe3b-2114-41b7-9856-711d4a99a379","num_tickets":1,"signature":"3045022100a2bc9be0d8f8f68c5224d0d7208c2956ab8503ce98a2fc460a0f13fef21fb5cc022027b6635b6f6c88d9d795b4da48e8a15ecc997f6153cbe68605b5477affa7080f"}```

**Comment by Krakaw** [comment]
I used the 420-transfer-tix branch sent myself a transfer and accepted the tickets without an issue. However the app did have a little wobble if no email or sms was present (uncaught exception).
I think the issue above could have been caused either by trying to accept tickets that were already accepted (by sending them to the same account and accepting the transfer) or re-transferring sent tickets.
Re-open this if you run into the problem again.
![screenshot 2019-01-09 at 10 56 59](https://user-images.githubusercontent.com/41575888/50888031-5974ef00-13fd-11e9-8ea4-5d0589dc8d4f.png)
