### ISSUE TITLE
Event Details - Displayed price ranges inconsistent related to listed tickets

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-api#877]
Shows $5-$15 but the ticket price on the event detail page is $10
<img width="1317" alt="big_neon_-_the_new_standard_in_event_ticketing" src="https://user-images.githubusercontent.com/456953/51226495-90b73480-1904-11e9-9149-571e7b0bf4c5.png">
<img width="1435" alt="vibe_vessel_tickets_on_big_neon" src="https://user-images.githubusercontent.com/456953/51226526-a4629b00-1904-11e9-943f-0a2a9c60bd5a.png">

**Comment by Krakaw** [comment]
@zmelamed Do you want it to only show what ticket prices are only available as of right now, not what the total possible price range is?
