### ISSUE TITLE
Box Office Hold - The max per order on this hold is 4. I allocated one, then went back to allocate 2 more and got the error message that it exceeded the limit.

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-api#891]
[https://www.bugherd.com/projects/154576/tasks/14](https://www.bugherd.com/projects/154576/tasks/14)

**Comment by Krakaw** [comment]
@zmelamed Should we allow box office to bypass ticket limit restrictions?

**Comment by mikethetike** [comment]
@zmelamed I have tried, but can't reproduce this error

**Comment by mikethetike** [comment]
It's actually a bug across the board. It would only look at the reserved time, which is why it always passed with new tickets
