### ISSUE TITLE
Cost in receipt email not to 2 dp

### ISSUE THREAD

**Issue by CjS77** [big-neon/bn-api#892]
> Your purchase of 2 item(s) for a total of $3.5 has been successfully completed on Big Neon.

Should be $3.50

**Comment by sdbondi** [comment]
Closing - this has been fixed by [583c9743ec67e68ef083718c26ee3412c4f8685b](https://github.com/big-neon/bn-api/commit/583c9743ec67e68ef083718c26ee3412c4f8685b)
