### ISSUE TITLE
Refunds: Refund email

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-api#905]
connects to big-neon/bigneon#82
In the initial refunds logic an email was added but I lacked sendgrid access to create a template for it. We'll need someone with access to the sendgrid account to create that email for the purposes of alerting customers of the refund and confirming the necessary information is present.

**Comment by mikethetike** [comment]
@Krakaw is this as simple as setting the ENV var on staging and testing it? ENV var is in the parent issue

**Comment by Krakaw** [comment]
The env's have been set
