### ISSUE TITLE
Allow admins, org owners, member etc permission to pull details for specific orders

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#909]
Previously an admin could view an order for another user with `/orders/{id}` but that permission seems to now be locked down.

Can we allow admins / org members access to that if they belong to the related org.

Currently breaking in bn-web: https://github.com/big-neon/bn-web/issues/991

**Comment by Timo614** [comment]
I think that endpoint has always been locked down to just the given user who made the purchase so may have been accessing from the same user previously?:
https://github.com/big-neon/bn-api/commit/fe46bcbcd073cdde5314ab39297183d873069e49

One thing we may have to do here is limit what's shown on the details by the user's access as an organization member accessing a given order likely should only be able to see the order information related to their own events.

We do have an order details endpoint that works that way but it breaks things apart per ticket so a bit different: `/orders/{id}/details` that was one of the requirements for the refund card previously as we refund based on an individual ticket at a time.

I'll grab this and adjust it accordingly based on the above.

**Comment by mikethetike** [comment]
Let's also add in another postman test after viewing the fan history:
![image](https://user-images.githubusercontent.com/4200336/51682605-79590500-1ff0-11e9-8d20-a2e1e7d3a290.png)
