### ISSUE TITLE
Events can be lost on admin page

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#943]
If you set an event start and an event end over a few days, the event shows up in neither upcoming or past events, effectively hiding the event from view until it completes.

**Comment by Timo614** [comment]
Should we introduce another filter for ongoing events? Or could rename upcoming and just include the current and future events there.

**Comment by Timo614** [comment]
For now going to add it to the upcoming response -- if it's worth breaking out into a separate response for just current events let me know but I figure given it's the admin section probably ideal to list the current along with the upcoming so the events in process and starting soon can be seen in one place.
