### ISSUE TITLE
Invite logic should prevent multiple records from being created

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-api#95]
We lack a unique constraint on the organization users and organization invites indexes so a duplicate record for the link could be added in the future by mistake. 

Not sure offhand looking over the invite logic if we need to do anything on the API side to handle this case. I think the code right now (haven't played around with it too much) may allow multiple entries for the same email for a given organization. May be worth adjusting it for the response so the frontend gets a conflict message in that case.

Similar issue to: #91

**Comment by mikethetike** [comment]
I think a new invite should expire old invites. You may want to resend an invite if the first email got blocked.
