### ISSUE TITLE
Drop the GET /status starting output

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#957]
It's spamming the logs

**Comment by Timo614** [comment]
@Krakaw should we keep this for the other endpoints and just remove it for the status endpoint or just remove it altogether?

Looks like it's this call in the middleware:
https://github.com/big-neon/bn-api/blob/99e9c47b98564514752ac3f90715b59c25fcac68/api/src/middleware/big_neon_logger.rs#L32

**Comment by Krakaw** [comment]
@mikethetike is this part of a greater logging plan? 
@Timo614 I'm going to close this issue for now and we can reopen it if it's just this endpoint that's spamming.
