### ISSUE TITLE
Org Roles - Create Promoter Admin and Promoter Read-Only Roles

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-api#996]
requires big-neon/bn-api#951
- When being invited the inviter should have to assign 1 to many events that the user can access
- Should not be able to access any view for the org outside of the event lists and individual event they have been granted access to
- Promoter Admin should have all the same event privileges as an Org Member to the events they've been granted access to (they should be able to modify events, but not create events)
- Promoter Read-Only should only be able to Access event dashboard, and view non-admin reports for the event. They should not be able to edit any aspect of the event. 

Promoter invitation flow UI to come soon

**Comment by Timo614** [comment]
Should be mostly set here with #1008 as it adds these two roles there.

> Promoter Read-Only should only be able to Access event dashboard, and view non-admin reports for the event. They should not be able to edit any aspect of the event.

What are the non-admin reports? The ones that are event level? Versus the organization level? Or are there public reports we're adding later and the current reports shouldn't be visible for the read only level.

**Comment by zmelamed** [comment]
Any reports that include fees should not be accessible. Event Summary, and transaction detail for instance.
